const navMenu=document.getElementById('js-nav-menu'),main=document.getElementById('js-main-content'),search=document.getElementById('search-input'),result=document.getElementById('search-result-info'),toast=document.getElementById('js-toast');
const VERSION='v2.6.6',THEME='chi-nav-theme';
let data=[],all=[],map=new Map(),favorites=getStoredFavorites(),recent=getStoredRecent(),active={};
function normalizeDescription(value){let text=String(value??'').replace(/\s+/g,' ').trim();if(!text)return text;text=text.replace(/[。！？.!?]+$/,'');return text+'。'}
function normalizeDescriptions(){data.forEach(s=>{if(s.links)s.links.forEach(l=>{l.description=normalizeDescription(l.description)});else(s.list||[]).forEach(group=>group.links?.forEach(l=>{l.description=normalizeDescription(l.description)}));})}
async function init(){const r=await fetch(`data/data.json?v=${VERSION}&t=${Date.now()}`,{cache:'no-store'});data=await r.json();normalizeDescriptions();data.forEach(s=>{if(s.links){s.links.forEach(l=>{l._taxonomy=s.taxonomy;l._term='常用';});}else{(s.list||[]).forEach(group=>group.links?.forEach(l=>{l._taxonomy=s.taxonomy;l._term=group.term;}));}flat(s).forEach(l=>{const k=key(l);if(!map.has(k))map.set(k,l);if(!all.some(x=>key(x)===k))all.push(l)});});favorites=normalizeFavorites(favorites,map);recent=normalizeRecent(recent,map);saveFavorites([...favorites]);saveRecent(recent);const versionLabel=document.getElementById('site-version');if(versionLabel)versionLabel.textContent=VERSION;home();initSearch();initSidebarToggle();
const params=new URLSearchParams(location.search),view=params.get('view'),action=params.get('action');if(view==='favorites'||view==='recent'||view==='recommendations')page(view);if(action==='search')openCommand();
document.querySelector('.brand')?.addEventListener('click',e=>{e.preventDefault();const s=document.querySelector('.sidebar');if(s?.classList.contains('collapsed')){s.classList.remove('collapsed');try{localStorage.setItem('chi-nav-sidebar-collapsed','0')}catch{}return}search.value='';result.textContent='';search.closest('.search-box')?.classList.remove('has-value');goHomeTo('top')});
document.querySelector('.brand')?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.click()}});
document.getElementById('search-clear')?.addEventListener('click',()=>{search.value='';result.textContent='';search.closest('.search-box')?.classList.remove('has-value');home();search.focus()});
document.addEventListener('click',async e=>{const f=e.target.closest('.favorite-btn');if(f){e.preventDefault();e.stopPropagation();const l=map.get(decodeURIComponent(f.closest('.card').dataset.key));if(l){favorites=toggleFavorite(l,favorites);home()}return}const tab=e.target.closest('[data-group][data-tab]');if(tab){active[tab.dataset.group]=tab.dataset.tab;home();return}const catTab=e.target.closest('[data-category-tab]');if(catTab){const g=GROUPS.find(x=>x.id===catTab.dataset.categoryTab);if(g){active[g.id]=catTab.dataset.tab;categoryPage(g.id)}return}const openCat=e.target.closest('[data-open-category]');if(openCat){categoryPage(openCat.dataset.openCategory);return}const back=e.target.closest('[data-home]');if(back){home();window.scrollTo({top:0,behavior:'smooth'});return}const q=e.target.closest('[data-quick]');if(q){e.preventDefault();if(q.dataset.quick==='command')openCommand();else if(q.dataset.quick==='recommendations')page('recommendations');else if(q.dataset.quick==='favorites')page('favorites');else if(q.dataset.quick==='recent')page('recent');return}const n=e.target.closest('[data-group-nav]');if(n){e.preventDefault();categoryPage(n.dataset.groupNav);return}const copy=e.target.closest('.copy-action');if(copy){e.preventDefault();const l=map.get(decodeURIComponent(copy.closest('.card').dataset.key));if(l?.copy_content){try{await navigator.clipboard.writeText(l.copy_content);showToast('腳本已複製','請到對應網頁開啟 Console 後貼上執行。')}catch{}}return}const link=e.target.closest('.card-link');if(link){const l=map.get(decodeURIComponent(link.closest('.card').dataset.key));if(l)recent=addRecent(l,recent);return}});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.sortable-card');if(!card)return;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.key);card.classList.add('dragging')});document.addEventListener('dragend',e=>e.target.closest('.card')?.classList.remove('dragging'));document.addEventListener('dragover',e=>{const card=e.target.closest('.sortable-card');if(!card)return;e.preventDefault();document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));card.classList.add('drag-over')});document.addEventListener('drop',e=>{const card=e.target.closest('.sortable-card');if(!card)return;e.preventDefault();const from=decodeURIComponent(e.dataTransfer.getData('text/plain')),to=decodeURIComponent(card.dataset.key);favorites=reorderFavorites(favorites,from,to);home()});
document.addEventListener('error',e=>{const img=e.target;if(!(img instanceof HTMLImageElement)||!img.dataset.fallback||img.dataset.fallbackUsed)return;img.dataset.fallbackUsed='1';img.src=img.dataset.fallback},true);
}
function showToast(title,desc){if(!toast)return;const t=toast.querySelector('.toast-title span'),d=toast.querySelector('.toast-desc');if(t)t.textContent=title;if(d)d.textContent=desc;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
init().then(checkVersion).catch(e=>{main.innerHTML='<div class="empty-state">無法載入 data.json，請檢查網站資料。</div>';console.error(e)})