function buildGroups(){return data.filter(s=>s?.taxonomy&&Array.isArray(s.list)&&s.list.length).map((s,i)=>({id:`group-${i}`,name:s.taxonomy,icon:String(s.icon||'fa-solid fa-layer-group').replace(/^fas\s+/,'fa-solid '),tabs:s.list.filter(g=>g?.term&&Array.isArray(g.links)).map(g=>[g.term,s.taxonomy,g.term])}));}
let GROUPS=[];
function refreshGroups(){GROUPS=buildGroups();}
function tabsFor(g){return g.tabs.filter(t=>tabData(g,t).length)}
function group(g){const list=tabsFor(g);if(!list.length)return '';const sel=active[g.id]&&list.some(x=>x[0]===active[g.id])?active[g.id]:list[0][0],t=list.find(x=>x[0]===sel)||list[0],content=tabData(g,t);active[g.id]=t[0];return `<section class="home-block launcher-section" id="group-${g.id}"><div class="launcher-page-head"><h2><i class="${esc(g.icon)}"></i>${esc(g.name)}</h2><button class="section-open" type="button" data-open-category="${esc(g.id)}">查看全部 <i class="fa-solid fa-arrow-right"></i></button></div><div class="home-block-tabs">${list.map(x=>`<button class="page-tab ${x[0]===t[0]?'active':''}" data-group="${esc(g.id)}" data-tab="${esc(x[0])}">${esc(x[0])}</button>`).join('')}</div><div class="home-block-body content-frame">${cards(content)}</div></section>`}
function restoreTopbar(){const topIntro=document.querySelector('.page-intro'),topSearch=document.querySelector('.topbar .search-box');if(topIntro)topIntro.style.display='';if(topSearch)topSearch.style.display='';}
function categoryPage(id){const g=GROUPS.find(x=>x.id===id);if(!g)return;const list=tabsFor(g);if(!list.length)return;const sel=active[g.id]&&list.some(x=>x[0]===active[g.id])?active[g.id]:list[0][0],t=list.find(x=>x[0]===sel)||list[0],content=tabData(g,t);active[g.id]=t[0];main.innerHTML=`<section class="launcher-page quick-page category-page" id="category-${esc(g.id)}"><div class="launcher-page-head"><h2><i class="${esc(g.icon)}"></i>${esc(g.name)}</h2></div><div class="category-page-search search-box" role="search"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input id="category-search-input" type="search" placeholder="搜尋網站、分類或關鍵字…" autocomplete="off" aria-label="搜尋網站、分類或關鍵字"><button class="search-clear" id="category-search-clear" type="button" aria-label="清除搜尋"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div><div class="category-subcategories">${list.map(x=>`<button class="page-tab ${x[0]===t[0]?'active':''}" type="button" data-category-tab="${esc(g.id)}" data-tab="${esc(x[0])}">${esc(x[0])}</button>`).join('')}</div><div class="category-page-body content-frame">${cards(content)}</div></section>`;sidebar();setPageTitle('Chi NAV','');const topIntro=document.querySelector('.page-intro');if(topIntro)topIntro.style.display='none';const topSearch=document.querySelector('.topbar .search-box');if(topSearch)topSearch.style.display='none';const input=document.getElementById('category-search-input'),clear=document.getElementById('category-search-clear');if(input){input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();const filtered=q?content.filter(l=>JSON.stringify(l).toLowerCase().includes(q)):content;const body=main.querySelector('.category-page-body');if(body)body.innerHTML=cards(filtered);if(clear)clear.classList.toggle('visible',!!q)});input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';input.dispatchEvent(new Event('input'))}});clear?.addEventListener('click',()=>{input.value='';input.dispatchEvent(new Event('input'));input.focus()})}}
function sidebar(){const groups=GROUPS.filter(g=>tabsFor(g).length);navMenu.innerHTML=(favorites.size?'<a class="nav-item quick-nav" href="#favorites" data-quick="favorites" title="我的收藏"><i class="fa-solid fa-star"></i><span>我的收藏</span></a>':'')+'<a class="nav-item quick-nav" href="#recommendations" data-quick="recommendations" title="常用"><i class="fa-solid fa-bolt"></i><span>常用</span></a><a class="nav-item quick-nav" href="#recent" data-quick="recent" title="最近使用"><i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span></a><div class="nav-divider"></div>'+groups.map(g=>`<a class="nav-item section-nav" href="#category-${g.id}" data-group-nav="${esc(g.id)}" title="${esc(g.name)}"><i class="${esc(g.icon)}"></i><span>${esc(g.name)}</span></a>`).join('')}
function page(type){restoreTopbar();const a=type==='favorites'?[...favorites].map(k=>map.get(k)).filter(Boolean):type==='recent'?recent.map(k=>map.get(k)).filter(Boolean):flat(src('常用推薦'));main.innerHTML=quick(type==='favorites'?'我的收藏':type==='recent'?'最近使用':'常用',type==='favorites'?'fa-solid fa-star':type==='recent'?'fa-solid fa-clock-rotate-left':'fa-solid fa-bolt',a,type);sidebar();setPageTitle(type==='favorites'?'我的收藏':type==='recent'?'最近使用':'常用','')}
function goHomeTo(targetId){home();requestAnimationFrame(()=>{const target=document.getElementById(targetId);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});else window.scrollTo({top:0,left:0,behavior:'smooth'})})}
function initSidebarToggle(){const sidebarEl=document.querySelector('.sidebar'),brand=document.getElementById('brand-home'),btn=document.getElementById('sidebar-toggle'),mark=document.querySelector('.brand-mark');if(!sidebarEl||!brand||!btn||!mark)return;const KEY='chi-nav-sidebar-collapsed';const set=(collapsed)=>{sidebarEl.classList.toggle('collapsed',collapsed);btn.innerHTML='<i class="fa-solid fa-grip-lines-vertical" aria-hidden="true"></i>';btn.setAttribute('aria-label',collapsed?'展開側邊欄':'收合側邊欄');btn.title=collapsed?'展開側邊欄':'收合側邊欄';brand.setAttribute('aria-label',collapsed?'展開側邊欄':'回到首頁');brand.setAttribute('role','button');brand.setAttribute('tabindex','0');try{localStorage.setItem(KEY,collapsed?'1':'0')}catch{}};let collapsed=false;try{collapsed=localStorage.getItem(KEY)==='1'}catch{}set(collapsed);btn.addEventListener('click',()=>set(true));brand.addEventListener('click',e=>{if(sidebarEl.classList.contains('collapsed')){e.preventDefault();set(false);return}home()});brand.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;e.preventDefault();if(sidebarEl.classList.contains('collapsed'))set(false);else home()});}
function setPageTitle(title,desc){const h=document.querySelector('.page-intro h2'),p=document.querySelector('.page-intro p');if(h)h.textContent=title;if(p)p.textContent=desc}
