function buildGroups(){return data.filter(s=>s?.taxonomy&&Array.isArray(s.list)&&s.list.length).map((s,i)=>({id:`group-${i}`,name:s.taxonomy,icon:String(s.icon||'fa-solid fa-layer-group').replace(/^fas\s+/,'fa-solid '),tabs:s.list.filter(g=>g?.term&&Array.isArray(g.links)).map(g=>[g.term,s.taxonomy,g.term])}));}
let GROUPS=[];
function refreshGroups(){GROUPS=buildGroups();}
function tabsFor(g){return g.tabs.filter(t=>tabData(g,t).length)}
function group(g){const list=tabsFor(g);if(!list.length)return '';const sel=active[g.id]&&list.some(x=>x[0]===active[g.id])?active[g.id]:list[0][0],t=list.find(x=>x[0]===sel)||list[0],content=tabData(g,t);active[g.id]=t[0];return `<section class="home-block" id="group-${g.id}"><div class="home-block-header"><div><span class="home-block-eyebrow">SECTION</span><h3><i class="${esc(g.icon)}"></i>${esc(g.name)}</h3></div><button class="section-open" type="button" data-open-category="${esc(g.id)}">查看全部 <i class="fa-solid fa-arrow-right"></i></button></div><div class="home-block-tabs">${list.map(x=>`<button class="page-tab ${x[0]===t[0]?'active':''}" data-group="${esc(g.id)}" data-tab="${esc(x[0])}">${esc(x[0])}</button>`).join('')}</div><div class="home-block-body content-frame">${cards(content)}</div></section>`}
function categoryPage(id){const g=GROUPS.find(x=>x.id===id);if(!g)return;const list=tabsFor(g);if(!list.length)return;const sel=active[g.id]&&list.some(x=>x[0]===active[g.id])?active[g.id]:list[0][0],t=list.find(x=>x[0]===sel)||list[0],content=tabData(g,t);active[g.id]=t[0];main.innerHTML=`<section class="launcher-page category-page"><div class="launcher-page-head category-hero"><button class="back-home" type="button" data-home><i class="fa-solid fa-arrow-left"></i> 返回首頁</button><div class="category-hero-icon" aria-hidden="true"><i class="${esc(g.icon)}"></i></div><span class="home-block-eyebrow">CATEGORY</span><h2>${esc(g.name)}</h2><p>${esc(t[0])} · ${content.length} 個網站</p></div><div class="home-block-tabs category-page-tabs"><span class="home-block-eyebrow subcategory-label">SUBCATEGORY</span>${list.map(x=>`<button class="page-tab ${x[0]===t[0]?'active':''}" type="button" data-category-tab="${esc(g.id)}" data-tab="${esc(x[0])}">${esc(x[0])}</button>`).join('')}</div><div class="content-frame category-all"><div class="grid">${content.map(l=>card(l)).join('')}</div></div></section>`;sidebar();setPageTitle(g.name,`${t[0]} · ${content.length} 個網站`);}
function sidebar(){const groups=GROUPS.filter(g=>tabsFor(g).length);navMenu.innerHTML=(favorites.size?'<a class="nav-item quick-nav" href="#favorites" data-quick="favorites" title="我的收藏"><i class="fa-solid fa-star"></i><span>我的收藏</span></a>':'')+'<a class="nav-item quick-nav" href="#recommendations" data-quick="recommendations" title="常用"><i class="fa-solid fa-bolt"></i><span>常用</span></a><a class="nav-item quick-nav" href="#recent" data-quick="recent" title="最近使用"><i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span></a><div class="nav-divider"></div>'+groups.map(g=>`<a class="nav-item section-nav" href="#category-${g.id}" data-group-nav="${esc(g.id)}" title="${esc(g.name)}"><i class="${esc(g.icon)}"></i><span>${esc(g.name)}</span></a>`).join('')}
function page(type){const a=type==='favorites'?[...favorites].map(k=>map.get(k)).filter(Boolean):type==='recent'?recent.map(k=>map.get(k)).filter(Boolean):flat(src('常用推薦'));main.innerHTML=quick(type==='favorites'?'我的收藏':type==='recent'?'最近使用':'常用',type==='favorites'?'fa-solid fa-star':type==='recent'?'fa-solid fa-clock-rotate-left':'fa-solid fa-bolt',a,type);sidebar();setPageTitle(type==='favorites'?'我的收藏':type==='recent'?'最近使用':'常用',type==='favorites'?`${a.length} 個收藏網站`:type==='recent'?`${a.length} 個最近使用的網站`:`${a.length} 個常用入口`)}
function goHomeTo(targetId){home();requestAnimationFrame(()=>{const target=document.getElementById(targetId);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});else window.scrollTo({top:0,left:0,behavior:'smooth'})})}
function initSidebarToggle(){const sidebarEl=document.querySelector('.sidebar'),brand=document.getElementById('brand-home'),btn=document.getElementById('sidebar-toggle'),mark=document.querySelector('.brand-mark');if(!sidebarEl||!brand||!btn||!mark)return;const KEY='chi-nav-sidebar-collapsed';const set=(collapsed)=>{sidebarEl.classList.toggle('collapsed',collapsed);btn.innerHTML='<i class="fa-solid fa-grip-lines-vertical" aria-hidden="true"></i>';btn.setAttribute('aria-label',collapsed?'展開側邊欄':'收合側邊欄');btn.title=collapsed?'展開側邊欄':'收合側邊欄';brand.setAttribute('aria-label',collapsed?'展開側邊欄':'回到首頁');brand.setAttribute('role','button');brand.setAttribute('tabindex','0');try{localStorage.setItem(KEY,collapsed?'1':'0')}catch{}};let collapsed=false;try{collapsed=localStorage.getItem(KEY)==='1'}catch{}set(collapsed);btn.addEventListener('click',()=>set(true));brand.addEventListener('click',e=>{if(sidebarEl.classList.contains('collapsed')){e.preventDefault();set(false);return}home()});brand.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;e.preventDefault();if(sidebarEl.classList.contains('collapsed'))set(false);else home()});}
function setPageTitle(title,desc){const h=document.querySelector('.page-intro h2'),p=document.querySelector('.page-intro p');if(h)h.textContent=title;if(p)p.textContent=desc}
