(()=>{
  const REPO='tsai97216/nav', DATA_PATH='data/data.json', KEY='chi-nav-quick-add-token';
  const css=`.quick-add-trigger{position:fixed;right:20px;bottom:20px;z-index:80;width:48px;height:48px;border:0;border-radius:16px;background:var(--accent,#356ae6);color:#fff;box-shadow:0 10px 28px rgba(0,0,0,.16);cursor:pointer;font-size:18px}.quick-add-trigger:hover{transform:translateY(-2px)}.quick-add-modal{position:fixed;inset:0;z-index:100;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(15,23,42,.38);backdrop-filter:blur(5px)}.quick-add-modal.show{display:flex}.quick-add-panel{width:min(560px,100%);max-height:min(760px,calc(100vh - 40px));overflow:auto;background:var(--surface,#fff);color:var(--text,#172033);border:1px solid var(--border,#e3e7ef);border-radius:22px;box-shadow:0 24px 80px rgba(0,0,0,.2);padding:24px}.quick-add-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.quick-add-head h3{margin:0;font-size:20px}.quick-add-close{border:0;background:transparent;color:inherit;font-size:22px;cursor:pointer}.quick-add-grid{display:grid;gap:13px}.quick-add-field{display:grid;gap:6px}.quick-add-field label{font-size:13px;font-weight:700}.quick-add-field input,.quick-add-field select,.quick-add-field textarea{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid var(--border,#dfe4ec);border-radius:11px;background:var(--input,#fff);color:inherit;font:inherit}.quick-add-field textarea{min-height:76px;resize:vertical}.quick-add-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:18px}.quick-add-actions button{border:0;border-radius:11px;padding:10px 16px;font-weight:700;cursor:pointer}.quick-add-cancel{background:transparent;color:inherit}.quick-add-submit{background:var(--accent,#356ae6);color:#fff}.quick-add-note{margin:0 0 15px;padding:10px 12px;border-radius:11px;background:rgba(53,106,230,.08);font-size:12px;line-height:1.55}.quick-add-status{min-height:18px;margin-top:10px;font-size:12px}.quick-add-token{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}@media(max-width:600px){.quick-add-trigger{right:14px;bottom:14px}.quick-add-panel{padding:18px;border-radius:18px}}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const button=document.createElement('button');button.className='quick-add-trigger';button.type='button';button.title='快速新增網站';button.setAttribute('aria-label','快速新增網站');button.innerHTML='<i class="fa-solid fa-plus"></i>';document.body.appendChild(button);
  const modal=document.createElement('div');modal.className='quick-add-modal';modal.innerHTML=`<section class="quick-add-panel" role="dialog" aria-modal="true" aria-labelledby="quick-add-title"><div class="quick-add-head"><h3 id="quick-add-title"><i class="fa-solid fa-bolt"></i> 快速新增網站</h3><button class="quick-add-close" type="button" aria-label="關閉">×</button></div><p class="quick-add-note">直接把網站加入指定分類並提交到 GitHub。Token 只存在本次瀏覽器分頁的 sessionStorage，不會寫進專案檔案。</p><form class="quick-add-grid"><div class="quick-add-field"><label>網站名稱</label><input name="title" required placeholder="例如：Speedtest"></div><div class="quick-add-field"><label>網址</label><input name="url" type="url" required placeholder="https://example.com"></div><div class="quick-add-field"><label>分類</label><select name="taxonomy" required></select></div><div class="quick-add-field"><label>子分類</label><select name="subcategory" required></select></div><div class="quick-add-field"><label>描述</label><textarea name="description" placeholder="簡短描述這個網站的用途"></textarea></div><div class="quick-add-field"><label>Icon（可選）</label><input name="icon" placeholder="fa-solid fa-globe" value="fa-solid fa-globe"></div><div class="quick-add-field"><label>GitHub Fine-grained Token</label><input class="quick-add-token" name="token" type="password" autocomplete="off" placeholder="輸入後僅本次分頁使用"></div><div class="quick-add-actions"><button class="quick-add-cancel" type="button">取消</button><button class="quick-add-submit" type="submit">新增並提交</button></div><div class="quick-add-status" aria-live="polite"></div></form></section>`;document.body.appendChild(modal);
  const form=modal.querySelector('form'),taxonomy=form.taxonomy,subcategory=form.subcategory,status=modal.querySelector('.quick-add-status'),tokenInput=form.token;
  const groups=()=>{try{return Array.isArray(data)?data:[]}catch{return[]}};
  function refreshTaxonomy(){taxonomy.innerHTML=groups().map(s=>`<option value="${escapeHtml(s.taxonomy)}">${escapeHtml(s.taxonomy)}</option>`).join('');refreshSubcategory();}
  function refreshSubcategory(){const s=groups().find(x=>x.taxonomy===taxonomy.value);const items=Array.isArray(s?.list)?s.list.map(x=>x.term):['常用'];subcategory.innerHTML=items.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function open(){refreshTaxonomy();try{tokenInput.value=sessionStorage.getItem(KEY)||''}catch{}status.textContent='';modal.classList.add('show');form.title.focus()}
  function close(){modal.classList.remove('show')}
  async function github(path,options={}){const token=tokenInput.value.trim();if(!token)throw new Error('請輸入 GitHub Token');const r=await fetch(`https://api.github.com/repos/${REPO}/contents/${path}?ref=main`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2026-03-10','Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){let msg=`GitHub API ${r.status}`;try{const j=await r.json();if(j.message)msg+=`: ${j.message}`}catch{}throw new Error(msg)}return r.json()}
  function decodeContent(encoded){const bin=atob(encoded.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
  function encodeContent(text){const bytes=new TextEncoder().encode(text);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
  form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),title=String(fd.get('title')||'').trim(),url=String(fd.get('url')||'').trim(),description=String(fd.get('description')||'').trim(),icon=String(fd.get('icon')||'fa-solid fa-globe').trim(),tax=String(fd.get('taxonomy')||''),sub=String(fd.get('subcategory')||'');if(!title||!url||!tax||!sub)return;try{new URL(url)}catch{status.textContent='網址格式不正確';return}status.textContent='正在讀取 data.json…';const current=await github(DATA_PATH);const remoteData=JSON.parse(decodeContent(current.content));if(!Array.isArray(remoteData))throw new Error('data.json 格式不是陣列');const section=remoteData.find(x=>x.taxonomy===tax);if(!section)throw new Error('找不到指定分類');const links=Array.isArray(section.links)?section.links:section.list?.find(x=>x.term===sub)?.links;if(!Array.isArray(links))throw new Error('找不到指定子分類');if(links.some(x=>x.url===url||x.title===title))throw new Error('同名稱或同網址已存在');links.push({title,url,description,icon});const body={message:`feat: quick add ${title}`,content:encodeContent(JSON.stringify(remoteData,null,2)+'\n'),sha:current.sha,branch:'main'};status.textContent='正在提交 GitHub…';await github(DATA_PATH,{method:'PUT',body:JSON.stringify(body)});try{sessionStorage.setItem(KEY,tokenInput.value.trim())}catch{}status.textContent='✓ 新增成功，GitHub Pages 更新後即可看到。';setTimeout(close,1200)}catch(err){console.error(err);status.textContent=`✗ ${err.message||'新增失敗'}`}});
  button.addEventListener('click',open);modal.querySelector('.quick-add-close').addEventListener('click',close);modal.querySelector('.quick-add-cancel').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});taxonomy.addEventListener('change',refreshSubcategory);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))close()});
})();
