function relativeTime(ts){if(!ts)return '';const d=Math.max(0,Date.now()-Number(ts)),m=Math.floor(d/60000),h=Math.floor(m/60),day=Math.floor(h/24);if(m<1)return '剛剛使用';if(m<60)return `${m} 分鐘前使用`;if(h<24)return `${h} 小時前使用`;if(day<7)return `${day} 天前使用`;return new Date(Number(ts)).toLocaleDateString('zh-TW')}
const ICON_SLUGS={
  'youtube.com':'youtube','music.youtube.com':'youtube-music','github.com':'github','google.com':'google','chat.openai.com':'openai','chatgpt.com':'openai','gemini.google.com':'googlegemini','claude.ai':'anthropic','deepseek.com':'deepseek','grok.com':'x','notion.so':'notion','app.notion.com':'notion','canva.com':'canva','pinterest.com':'pinterest','spotify.com':'spotify','open.spotify.com':'spotify','netflix.com':'netflix','twitch.tv':'twitch','bilibili.com':'bilibili','discord.com':'discord','discord.gg':'discord','cloudflare.com':'cloudflare','oracle.com':'oracle','steamcommunity.com':'steam','steampowered.com':'steam','reddit.com':'reddit','telegram.org':'telegram','facebook.com':'facebook','instagram.com':'instagram'
};
function iconUrl(host){const h=host.replace(/^www\./,'').toLowerCase(),slug=ICON_SLUGS[h];return slug?`https://cdn.simpleicons.org/${slug}`:`https://www.google.com/s2/favicons?sz=128&domain=${encodeURIComponent(h)}`}
function card(l,opts={}){const k=key(l),fav=favorites.has(k);let d='';try{d=new URL(l.url).hostname}catch{}const primary=d?iconUrl(d):'',fallback=d?`${new URL(l.url).origin}/favicon.ico`:'';const icon=d?`<img class="card-logo" src="${esc(primary)}" data-fallback="${esc(fallback)}" alt="" loading="lazy" decoding="async">`:`<span class="avatar-fallback">${esc((l.title||'?')[0])}</span>`;const validUrl=!!l.url&&l.url!=='javascript:void(0)';const action=l.is_copy?`<button class="copy-action" type="button" aria-label="複製 ${esc(l.title)}">${cardBody(l,icon,opts)}</button>`:validUrl?`<a class="card-link" href="${esc(l.url)}" target="_blank" rel="noopener noreferrer" aria-label="開啟 ${esc(l.title)}">${cardBody(l,icon,opts)}</a>`:`${cardBody(l,icon,opts)}`;return `<article class="card ${opts.sortable?'sortable-card':''}" data-key="${encodeURIComponent(k)}" data-copy="${l.is_copy?'1':'0'}" draggable="${opts.sortable?'true':'false'}"><button class="favorite-btn ${fav?'is-favorite':''}" type="button" aria-label="${fav?'取消收藏':'加入收藏'}"><i class="fa-${fav?'solid':'regular'} fa-star"></i></button>${l.is_copy?'<span class="copy-badge"><i class="fa-regular fa-copy"></i> 腳本</span>':''}${action}</article>`}
function cardBody(l,icon,opts){const category=opts.search&&l._taxonomy?`<div class="card-meta">${esc(l._taxonomy)}${l._term?` <span>·</span> ${esc(l._term)}`:''}</div>`:'';return `<div class="card-top"><div class="card-logo-container">${icon}</div><div class="card-title">${esc(l.title)}</div></div>${l.description?`<div class="card-desc">${esc(l.description)}</div>`:''}${category}${opts.recent?`<div class="recent-time">${relativeTime(loadRecentTimes()[key(l)])}</div>`:''}`}
function cards(a,allow=true,opts={}){const x=uniq(a).filter(l=>allow||!favorites.has(key(l)));return x.length?`<div class="grid">${x.map(l=>card(l,opts)).join('')}</div>`:'<div class="empty-state">目前沒有內容。</div>'}
function quick(title,icon,a,id){const opts={sortable:id==='favorites',recent:id==='recent',search:id==='search'};return `<section class="home-block" id="${id}"><div class="home-block-header"><div><span class="home-block-eyebrow">${id==='recent'?'RECENT':'PERSONAL'}</span><h3><i class="${icon}"></i>${title}</h3></div></div>${id==='search'?'<div class="search-result-meta"></div>':''}<div class="home-block-body content-frame">${cards(a,true,opts)}</div></section>`}
function home(){const fav=[...favorites].map(k=>map.get(k)).filter(Boolean),rec=flat(src('常用推薦')).filter(l=>!favorites.has(key(l))),r=recent.map(k=>map.get(k)).filter(Boolean);main.innerHTML=(fav.length?quick('我的收藏','fa-solid fa-star',fav,'favorites'):'')+quick('常用','fa-solid fa-bolt',rec,'recommendations')+(r.length?quick('最近使用','fa-solid fa-clock-rotate-left',r,'recent'):'')+GROUPS.map(group).join('');const intro=document.querySelector('.page-intro h2');if(intro)intro.textContent='Chi 的工具箱';const desc=document.querySelector('.page-intro p');if(desc)desc.textContent='常用網站與各個內容區塊，都可以直接在這裡瀏覽。';sidebar()}
