const navMenu=document.getElementById("js-nav-menu");
const mainContent=document.getElementById("js-main-content");
const quickSections=document.getElementById("quick-sections");
const searchInput=document.getElementById("search-input");
const resultInfo=document.getElementById("search-result-info");
const FAVORITES_KEY="chi-nav-favorites",RECENT_KEY="chi-nav-recent",RECENT_LIMIT=8;
const NAV_GROUPS=[
{name:"常用",icon:"fa-solid fa-star",sections:["常用推薦"]},
{name:"娛樂",icon:"fa-solid fa-gamepad",sections:["遊戲工具","影音娛樂","社群網路","二次元內容"]},
{name:"工具",icon:"fa-solid fa-toolbox",sections:["人工智慧","實用工具","文字與中文工具","資訊安全","進階工具","腳本工具"]},
{name:"服務",icon:"fa-solid fa-server",sections:["雲端服務"]}
];
let sections=[],allLinks=[];const linkMap=new Map();let favorites=new Set(loadStorage(FAVORITES_KEY)),recent=loadStorage(RECENT_KEY);
const fallbackColors=["linear-gradient(135deg,#3b82f6,#1d4ed8)","linear-gradient(135deg,#10b981,#047857)","linear-gradient(135deg,#8b5cf6,#6d28d9)","linear-gradient(135deg,#f59e0b,#b45309)","linear-gradient(135deg,#ec4899,#be185d)","linear-gradient(135deg,#14b8a6,#0f766e)","linear-gradient(135deg,#ef4444,#b91c1c)"];
function loadStorage(key){try{const v=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(v)?v:[]}catch(e){return[]}}
function saveStorage(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch(e){}}
function linkKey(link){return `${link.title}||${link.url}`}
function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function colorFor(title){let h=0;for(let i=0;i<title.length;i++)h=title.charCodeAt(i)+((h<<5)-h);return fallbackColors[Math.abs(h)%fallbackColors.length]}
function getDomain(url){try{return url.startsWith("http")?new URL(url).hostname:""}catch(e){return""}}
function createCard(link){
 const key=linkKey(link),domain=getDomain(link.url),fav=favorites.has(key),title=escapeHtml(link.title),desc=escapeHtml(link.description||""),letter=escapeHtml((link.title||"?").charAt(0));
 const favicon=domain?`<img class="card-logo" src="https://www.google.com/s2/favicons?sz=128&domain=${encodeURIComponent(domain)}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:"";
 const fallback=`<span class="avatar-fallback" style="${domain?"display:none":""}">${letter}</span>`;
 return `<article class="card" data-key="${encodeURIComponent(key)}" data-copy-enabled="${link.is_copy?"true":"false"}" data-search="${escapeHtml(`${link.title} ${link.description||""}`.toLowerCase())}"><button class="favorite-btn ${fav?"is-favorite":""}" type="button" aria-label="${fav?"取消收藏":"加入收藏"}"><i class="fa-${fav?"solid":"regular"} fa-star"></i></button>${link.is_copy?'<span class="copy-badge"><i class="fa-regular fa-copy"></i> 腳本</span>':""}<div class="card-top"><div class="card-logo-container" style="background:${colorFor(link.title||"?")}">${favicon}${fallback}</div><div class="card-title">${title}</div></div>${desc?`<div class="card-desc">${desc}</div>`:""}</article>`;
}
function renderNav(){
 navMenu.innerHTML="";
 if(favorites.size||recent.length)navMenu.insertAdjacentHTML("beforeend",'<div class="nav-divider"></div>');
 if(favorites.size){const a=document.createElement("a");a.className="nav-item quick-nav";a.href="#section-favorites";a.innerHTML='<i class="fa-solid fa-star"></i><span>我的收藏</span>';navMenu.appendChild(a)}
 if(recent.length){const a=document.createElement("a");a.className="nav-item quick-nav";a.href="#section-recent";a.innerHTML='<i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span>';navMenu.appendChild(a)}
 if(favorites.size||recent.length)navMenu.insertAdjacentHTML("beforeend",'<div class="nav-divider"></div>');
 const used=new Set();
 NAV_GROUPS.forEach(group=>{const matched=sections.map((s,i)=>({s,i})).filter(x=>group.sections.includes(x.s.taxonomy));if(!matched.length)return;const label=document.createElement("div");label.className="nav-group-title";label.innerHTML=`<i class="${group.icon}"></i><span>${group.name}</span>`;navMenu.appendChild(label);matched.forEach(({s,i})=>{used.add(i);const a=document.createElement("a");a.className="nav-item category-nav";a.href=`#section-${i}`;a.dataset.section=s.taxonomy;a.innerHTML=`<i class="${escapeHtml(s.icon)}"></i><span>${escapeHtml(s.taxonomy)}</span>`;navMenu.appendChild(a)})});
 const others=sections.map((s,i)=>({s,i})).filter(x=>!used.has(x.i));
 if(others.length){const label=document.createElement("div");label.className="nav-group-title";label.innerHTML='<i class="fa-solid fa-folder"></i><span>其他</span>';navMenu.appendChild(label);others.forEach(({s,i})=>{const a=document.createElement("a");a.className="nav-item category-nav";a.href=`#section-${i}`;a.dataset.section=s.taxonomy;a.innerHTML=`<i class="${escapeHtml(s.icon)}"></i><span>${escapeHtml(s.taxonomy)}</span>`;navMenu.appendChild(a)})}
}
function renderQuickSections(){const favLinks=allLinks.filter(l=>favorites.has(linkKey(l))),recentLinks=recent.map(k=>linkMap.get(k)).filter(Boolean);let html="";if(favLinks.length)html+=`<section class="section quick-section" id="section-favorites"><div class="section-header"><i class="fa-solid fa-star"></i><span>我的收藏</span></div><div class="grid">${favLinks.map(createCard).join("")}</div></section>`;if(recentLinks.length)html+=`<section class="section quick-section" id="section-recent"><div class="section-header"><i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span></div><div class="grid">${recentLinks.map(createCard).join("")}</div></section>`;quickSections.innerHTML=html;renderNav()}
function renderContent(){mainContent.innerHTML="";sections.forEach((s,i)=>{const el=document.createElement("section");el.className="section";el.id=`section-${i}`;el.dataset.taxonomy=s.taxonomy;let html=`<div class="section-header"><i class="${escapeHtml(s.icon)}"></i><span>${escapeHtml(s.taxonomy)}</span></div>`;if(Array.isArray(s.list))s.list.forEach(g=>{const links=Array.isArray(g.links)?g.links:[];if(links.length)html+=`<div class="term-container"><div class="term-title">${escapeHtml(g.term||"")}</div><div class="grid">${links.map(createCard).join("")}</div></div>`});else if(Array.isArray(s.links))html+=`<div class="grid">${s.links.map(createCard).join("")}</div>`;el.innerHTML=html;mainContent.appendChild(el)})}
function refreshFavoriteButtons(){document.querySelectorAll(".favorite-btn").forEach(b=>{const c=b.closest(".card");if(!c)return;const active=favorites.has(decodeURIComponent(c.dataset.key||""));b.classList.toggle("is-favorite",active);b.setAttribute("aria-label",active?"取消收藏":"加入收藏");b.innerHTML=`<i class="fa-${active?"solid":"regular"} fa-star"></i>`})}
function toggleFavorite(link){const k=linkKey(link);favorites.has(k)?favorites.delete(k):favorites.add(k);saveStorage(FAVORITES_KEY,[...favorites]);renderQuickSections();refreshFavoriteButtons();applySearch(searchInput.value)}
function addRecent(link){const k=linkKey(link);recent=[k,...recent.filter(x=>x!==k)].slice(0,RECENT_LIMIT);saveStorage(RECENT_KEY,recent);renderQuickSections()}
function applySearch(value){const q=value.trim().toLowerCase();let count=0;quickSections.style.display=q?"none":"block";document.querySelectorAll(".section:not(.quick-section)").forEach(section=>{let n=0;section.querySelectorAll(".term-container").forEach(term=>{let m=0;term.querySelectorAll(".card").forEach(c=>{const ok=!q||(c.dataset.search||"").includes(q);c.style.display=ok?"":"none";if(ok){m++;count++}});term.style.display=m?"":"none";n+=m});const grid=section.querySelector(":scope > .grid");if(grid)grid.querySelectorAll(".card").forEach(c=>{const ok=!q||(c.dataset.search||"").includes(q);c.style.display=ok?"":"none";if(ok){n++;count++}});section.style.display=n?"":"none";const nav=[...document.querySelectorAll(".category-nav")].find(x=>x.dataset.section===section.dataset.taxonomy);if(nav)nav.style.display=n?"":"none"});if(q){resultInfo.textContent=`找到 ${count} 個結果`;resultInfo.style.display="inline"}else{resultInfo.textContent="";resultInfo.style.display="none";document.querySelectorAll(".category-nav").forEach(n=>n.style.display="")}}
function setActiveNav(){let current="";for(const s of [...document.querySelectorAll(".section")].filter(x=>x.style.display!=="none"))if(scrollY>=s.offsetTop-100)current=s.id;document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));const a=document.querySelector(`.nav-item[href="#${current}"]`);if(a)a.classList.add("active")}
async function init(){try{const r=await fetch("data.json",{cache:"no-cache"});if(!r.ok)throw Error(`HTTP ${r.status}`);sections=await r.json();allLinks=[];linkMap.clear();sections.forEach(s=>{const links=[];if(Array.isArray(s.links))links.push(...s.links);if(Array.isArray(s.list))s.list.forEach(g=>links.push(...(g.links||[])));links.forEach(l=>{allLinks.push(l);linkMap.set(linkKey(l),l)})});renderContent();renderQuickSections();applySearch("");searchInput.addEventListener("input",()=>applySearch(searchInput.value));document.addEventListener("keydown",e=>{const a=document.activeElement,typing=a&&(["INPUT","TEXTAREA"].includes(a.tagName)||a.isContentEditable);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchInput.focus();searchInput.select()}else if(e.key==="/"&&!typing){e.preventDefault();searchInput.focus()}else if(e.key==="Escape"&&a===searchInput){searchInput.value="";applySearch("");searchInput.blur()}});document.addEventListener("click",e=>{const fav=e.target.closest(".favorite-btn");if(fav){e.preventDefault();e.stopPropagation();const c=fav.closest(".card"),l=linkMap.get(decodeURIComponent(c?.dataset.key||""));if(l)toggleFavorite(l);return}const c=e.target.closest(".card");if(!c)return;const l=linkMap.get(decodeURIComponent(c.dataset.key||""));if(!l)return;if(c.dataset.copyEnabled==="true"){navigator.clipboard.writeText(l.copy_content||"").then(()=>{const t=document.getElementById("js-toast");t.classList.add("show");clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove("show"),4000)})}else if(l.url&&l.url!=="javascript:void(0);"){addRecent(l);window.open(l.url,"_blank","noopener,noreferrer")}});addEventListener("scroll",setActiveNav,{passive:true})}catch(e){console.error(e);mainContent.innerHTML='<div class="empty-state">無法載入網站資料，請重新整理頁面。</div>'}}
init();
