const navMenu=document.getElementById("js-nav-menu"),mainContent=document.getElementById("js-main-content"),quickSections=document.getElementById("quick-sections"),searchInput=document.getElementById("search-input"),resultInfo=document.getElementById("search-result-info"),toast=document.getElementById("js-toast");
const FAVORITES_KEY="chi-nav-favorites",RECENT_KEY="chi-nav-recent",RECENT_LIMIT=8;
const HOME_BLOCKS=["遊戲","二次元","影音與音樂","社群與論壇","AI","搜尋與資訊","檔案","文件與轉換","翻譯","創作工具","文字與實用工具","開發","資安與資料","iOS 工具","雲端與個人服務","我的腳本"];
let sections=[],allLinks=[],favorites=new Set(loadStorage(FAVORITES_KEY)),recent=loadStorage(RECENT_KEY),linkMap=new Map(),homeSubs={};
const fallbackColors=["linear-gradient(135deg,#3b82f6,#1d4ed8)","linear-gradient(135deg,#10b981,#047857)","linear-gradient(135deg,#8b5cf6,#6d28d9)","linear-gradient(135deg,#f59e0b,#b45309)","linear-gradient(135deg,#ec4899,#be185d)","linear-gradient(135deg,#14b8a6,#0f766e)","linear-gradient(135deg,#ef4444,#b91c1c)"];
function loadStorage(key){try{const v=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(v)?v:[]}catch(e){return[]}}
function saveStorage(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch(e){}}
function normalizeUrl(url){try{const u=new URL(url,location.href);if(u.protocol==="http:"||u.protocol==="https:"){u.hash="";u.hostname=u.hostname.toLowerCase();if((u.protocol==="http:"&&u.port==="80")||(u.protocol==="https:"&&u.port==="443"))u.port="";u.pathname=u.pathname.replace(/\/{2,}/g,"/").replace(/\/$/,"")||"/";return u.toString()}return String(url).trim()}catch(e){return String(url||"").trim()}}
function linkKey(link){return normalizeUrl(link.url)}
function migrateKeys(values){return values.map(v=>typeof v==="string"?normalizeUrl(v):null).filter(Boolean)}
function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function colorFor(title){let h=0;for(let i=0;i<title.length;i++)h=title.charCodeAt(i)+((h<<5)-h);return fallbackColors[Math.abs(h)%fallbackColors.length]}
function getDomain(url){try{return url.startsWith("http")?new URL(url).hostname:""}catch(e){return""}}
function getSection(t){return sections.find(s=>s.taxonomy===t)}
function getTabs(s){return s&&Array.isArray(s.list)?s.list.map(g=>({id:g.term,name:g.term,icon:s.taxonomy==="遊戲"?"fa-solid fa-gamepad":s.icon})):[]}
function isHiddenFromRecommendations(link,t){return t==="常用推薦"&&favorites.has(linkKey(link))}
function createCard(link){const key=linkKey(link),domain=getDomain(link.url),fav=favorites.has(key),title=escapeHtml(link.title),desc=escapeHtml(link.description||""),letter=escapeHtml((link.title||"?").charAt(0));const favicon=domain?`<img class="card-logo" src="https://www.google.com/s2/favicons?sz=128&domain=${encodeURIComponent(domain)}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:"";const fallback=`<span class="avatar-fallback" style="${domain?"display:none":""}">${letter}</span>`;return `<article class="card" data-key="${encodeURIComponent(key)}" data-copy-enabled="${link.is_copy?"true":"false"}"><button class="favorite-btn ${fav?"is-favorite":""}" type="button" aria-label="${fav?"取消收藏":"加入收藏"}"><i class="fa-${fav?"solid":"regular"} fa-star"></i></button>${link.is_copy?'<span class="copy-badge"><i class="fa-regular fa-copy"></i> 腳本</span>':""}<div class="card-top"><div class="card-logo-container" style="background:${colorFor(link.title||"?")}">${favicon}${fallback}</div><div class="card-title">${title}</div></div>${desc?`<div class="card-desc">${desc}</div>`:""}</article>`}
function renderNav(){navMenu.innerHTML=`<a class="nav-item active" href="#home"><i class="fa-solid fa-house"></i><span>首頁</span></a>`;if(favorites.size||recent.length)navMenu.insertAdjacentHTML("beforeend",'<div class="nav-divider"></div>');if(favorites.size)navMenu.insertAdjacentHTML("beforeend",'<a class="nav-item quick-nav" href="#favorites" data-quick="favorites"><i class="fa-solid fa-star"></i><span>我的收藏</span></a>');if(recent.length)navMenu.insertAdjacentHTML("beforeend",'<a class="nav-item quick-nav" href="#recent" data-quick="recent"><i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span></a>')}
function renderCards(s,sub=""){if(!s)return"";if(Array.isArray(s.links)){const links=s.links.filter(l=>!isHiddenFromRecommendations(l,s.taxonomy));return `<div class="grid">${links.map(createCard).join("")}</div>`}const g=s.list?.find(x=>x.term===sub)||s.list?.[0],links=(g?.links||[]).filter(l=>!isHiddenFromRecommendations(l,s.taxonomy));return `<div class="grid">${links.map(createCard).join("")}</div>`}
function renderHomeBlock(t){const s=getSection(t);if(!s)return"";const tabs=getTabs(s);let sub=homeSubs[t]||tabs[0]?.id||"";if(tabs.length&&!tabs.some(x=>x.id===sub))sub=tabs[0].id;homeSubs[t]=sub;const isGame=t==="遊戲";const tabsHtml=tabs.length>1?`<div class="home-block-tabs">${tabs.map(x=>`<button class="page-tab ${sub===x.id?"active":""}" data-home-section="${escapeHtml(t)}" data-home-sub="${escapeHtml(x.id)}"><i class="${escapeHtml(x.icon)}"></i><span>${escapeHtml(x.name)}</span></button>`).join("")}</div>`:"";return `<section class="home-block ${isGame?"home-game-block":""}" id="section-${encodeURIComponent(t)}"><div class="home-block-header"><div><span class="home-block-eyebrow">SECTION</span><h3><i class="${escapeHtml(s.icon)}"></i>${escapeHtml(t)}</h3></div>${tabs.length>1?`<span class="home-block-page">${escapeHtml(sub)}</span>`:""}</div>${tabsHtml}<div class="home-block-body ${isGame?"game-frame":"content-frame"}">${isGame?`<div class="game-frame-title"><i class="fa-solid fa-gamepad"></i><span>遊戲</span><small>${escapeHtml(sub)}</small></div>`:""}${renderCards(s,sub)}</div></section>`}
function renderHome(){let html="";const favLinks=[...favorites].map(k=>linkMap.get(k)).filter(Boolean),recentLinks=recent.map(k=>linkMap.get(k)).filter(Boolean);if(favLinks.length)html+=`<section class="section quick-section"><div class="section-header"><i class="fa-solid fa-star"></i><span>我的收藏</span></div><div class="grid">${favLinks.map(createCard).join("")}</div></section>`;if(recentLinks.length)html+=`<section class="section quick-section"><div class="section-header"><i class="fa-solid fa-clock-rotate-left"></i><span>最近使用</span></div><div class="grid">${recentLinks.map(createCard).join("")}</div></section>`;const rec=getSection("常用推薦");if(rec){const links=(rec.links||[]).filter(l=>!isHiddenFromRecommendations(l,"常用推薦"));if(links.length)html+=`<section class="section quick-section"><div class="section-header"><i class="fa-solid fa-star"></i><span>常用推薦</span></div><div class="grid">${links.map(createCard).join("")}</div></section>`}HOME_BLOCKS.forEach(t=>html+=renderHomeBlock(t));mainContent.innerHTML=html||'<div class="empty-state">目前沒有內容。</div>';renderNav()}
function renderSearchResults(q){document.querySelector(".page-intro h2").textContent="搜尋結果";document.querySelector(".page-intro p").textContent="在所有網站中搜尋。";const matches=allLinks.filter(l=>`${l.title} ${l.description||""}`.toLowerCase().includes(q));resultInfo.textContent=`找到 ${matches.length} 個結果`;mainContent.innerHTML=matches.length?`<section class="section"><div class="search-result-frame"><div class="section-header"><i class="fa-solid fa-magnifying-glass"></i><span>搜尋結果</span></div><div class="grid">${matches.map(createCard).join("")}</div></div></section>`:'<div class="empty-state">找不到符合的網站。</div>';renderNav()}
function toggleFavorite(link){const k=linkKey(link);favorites.has(k)?favorites.delete(k):favorites.add(k);saveStorage(FAVORITES_KEY,[...favorites]);renderHome()}
function addRecent(link){const k=linkKey(link);recent=[k,...recent.filter(x=>x!==k)].slice(0,RECENT_LIMIT);saveStorage(RECENT_KEY,recent);renderNav()}
function openQuick(type){document.querySelector(".page-intro h2").textContent=type==="favorites"?"我的收藏":"最近使用";document.querySelector(".page-intro p").textContent=type==="favorites"?"你標記的常用網站。":"最近開啟過的網站。";const keys=type==="favorites"?[...favorites]:recent,links=keys.map(k=>linkMap.get(k)).filter(Boolean);mainContent.innerHTML=links.length?`<section class="section quick-section"><div class="grid">${links.map(createCard).join("")}</div></section>`:'<div class="empty-state">目前沒有內容。</div>';quickSections.innerHTML="";renderNav()}
function applySearch(value){const q=value.trim().toLowerCase();if(q){quickSections.innerHTML="";renderSearchResults(q)}else{resultInfo.textContent="";document.querySelector(".page-intro h2").textContent="首頁";document.querySelector(".page-intro p").textContent="常用網站與各個內容區塊，都可以直接在這裡瀏覽。";renderHome()}}
function showToast(){if(!toast)return;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
async function init(){try{const r=await fetch("data.json",{cache:"no-cache"});if(!r.ok)throw Error(`HTTP ${r.status}`);sections=await r.json();allLinks=[];linkMap.clear();sections.forEach(s=>{const links=[];if(Array.isArray(s.links))links.push(...s.links);if(Array.isArray(s.list))s.list.forEach(g=>links.push(...(g.links||[])));links.forEach(l=>{const k=linkKey(l);if(!linkMap.has(k))linkMap.set(k,l);if(!allLinks.some(x=>linkKey(x)===k))allLinks.push(l)})});favorites=new Set(migrateKeys([...favorites]).filter(k=>linkMap.has(k)));recent=[...new Set(migrateKeys(recent).filter(k=>linkMap.has(k)))].slice(0,RECENT_LIMIT);saveStorage(FAVORITES_KEY,[...favorites]);saveStorage(RECENT_KEY,recent);renderHome();searchInput.addEventListener("input",()=>applySearch(searchInput.value));document.addEventListener("click",async e=>{const fav=e.target.closest(".favorite-btn");if(fav){e.preventDefault();e.stopPropagation();const card=fav.closest(".card"),link=linkMap.get(decodeURIComponent(card.dataset.key));if(link)toggleFavorite(link);return}const tab=e.target.closest("[data-home-section]");if(tab){homeSubs[tab.dataset.homeSection]=tab.dataset.homeSub;renderHome();requestAnimationFrame(()=>document.getElementById(`section-${encodeURIComponent(tab.dataset.homeSection)}`)?.scrollIntoView({block:"nearest",behavior:"smooth"}));return}const quick=e.target.closest("[data-quick]");if(quick){e.preventDefault();openQuick(quick.dataset.quick);return}const card=e.target.closest(".card");if(card){const link=linkMap.get(decodeURIComponent(card.dataset.key));if(!link)return;if(card.dataset.copyEnabled==="true"&&link.script){try{await navigator.clipboard.writeText(link.script);showToast()}catch(err){}}else if(link.url&&link.url!=="javascript:void(0)"){addRecent(link);window.open(link.url,"_blank","noopener,noreferrer")}}});document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchInput.focus()}if(e.key==="Escape"&&document.activeElement===searchInput){searchInput.value="";applySearch("")}});renderNav()}catch(e){mainContent.innerHTML='<div class="empty-state">無法載入 data.json，請檢查網站資料。</div>';console.error(e)}}
init();