const CACHE_NAME="chi-nav-clean-cache-v2";
const CORE_ASSETS=["./","./index.html","./css/style.css","./css/responsive.css","./css/theme.css","./css/update.css","./css/card-tooltip.css","./css/enhancements.css","./css/loading.css","./css/category-page.css","./css/design-system.css","./css/card-layout.css","./js/utils.js","./js/data.js","./js/storage.js","./js/update.js","./js/search.js","./js/navigation.js","./js/render.js","./js/app.js","./js/theme.js","./js/card-tooltip.js","./js/bootstrap.js","./data/data.json","./manifest.json","./assets/icon/icon-bw.png","./assets/icon/icon-wb.png"];
const NETWORK_FIRST=["/","/index.html","/data/data.json","/manifest.json"];\nconst NETWORK_FIRST_EXTENSIONS=[".css",".js"];
const CACHE_FIRST_EXTENSIONS=[".css",".js",".svg",".png",".jpg",".jpeg",".webp",".ico",".woff",".woff2"];
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(CORE_ASSETS.map(url=>new Request(url,{cache:"reload"})))).then(()=>self.skipWaiting()))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("chi-nav-")&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function networkFirst(request){try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}catch{const cached=await caches.match(request);if(cached)return cached;if(request.mode==="navigate"){const fallback=await caches.match("./index.html");if(fallback)return fallback}throw new Error("Network unavailable and no cached response")}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}catch{throw new Error("Resource unavailable")}}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;const path=url.pathname;const isNetworkFirst=NETWORK_FIRST.some(item=>path===item||path.endsWith(item))||NETWORK_FIRST_EXTENSIONS.some(extension=>path.endsWith(extension));const isCacheFirst=!isNetworkFirst&&CACHE_FIRST_EXTENSIONS.some(extension=>path.endsWith(extension));if(isNetworkFirst){event.respondWith(networkFirst(event.request));return}if(isCacheFirst)event.respondWith(cacheFirst(event.request))}});
